MyProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as authentication_views
from users.views import (
    register,
    view_profile,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include("food.urls")),
    path('register/', register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('profile/', view_profile, name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyProject/food/urls.py
from django.urls import path
from . import views
 
app_name = "food"
urlpatterns = [
    # path("", views.index, name='index'),
    path("", views.IndexClassView.as_view(), name='index'),
    # path("detail-view/<int:item_id>/", views.detail_view, name='detail'),
    path("detail-view/<int:pk>/", views.DetailClassView.as_view(), name='detail'),
    path("add-item/", views.CreateItemView.as_view(), name='create_item'),
    path("update-item/<int:item_id>/", views.update_item, name='update_item'),
    path("delete-item/<int:item_id>/", views.delete_item, name='delete_item'),
]

MyProject/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Items(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=120)
    item_desc = models.CharField(max_length=120)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="shorturl.at/gzR34")

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

MyProject/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=120)

    def __str__(self):
        return self.user.username

MyProject/food/forms.py
from django import forms
from .models import Items


class ItemForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

MyProject/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

MyProject/food/views.py
from pyexpat import model

from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import Items
from .forms import ItemForm
from django.views.generic.list import ListView


# Create your views here.
def index(request):
    item_list = Items.objects.all()
    context = {
        "item_list": item_list,
    }
    return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Items
    template_name = 'food/index.html'
    context_object_name = "item_list"


def detail_view(request, item_id):
    item = Items.objects.get(id=item_id)
    context = {
        "item": item,
    }
    return render(request, 'food/detail.html', context)


class DetailClassView(DetailView):
    model = Items
    template_name = "food/detail.html"
    context_object_name = 'item'


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    context = {
        "form": form,
    }
    return render(request, 'food/item_form.html', context)


class CreateItemView(CreateView):
    model = Items
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template = 'food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, item_id):
    item = Items.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    context = {
        "form": form,
        "item": item,
    }
    return render(request, 'food/item_form.html', context)


def delete_item(request, item_id):
    item = Items.objects.get(id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    context = {
        "item": item,
    }
    return render(request, 'food/item_delete.html', context)

MyProject/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.


def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        messages.success(request, f"Welcome {username}. Your account has been created!")
        return redirect("login")
    context = {
        "form": form,
    }
    return render(request, 'users/register.html', context)


@login_required
def view_profile(request):
    return render(request, 'users/profile.html', {})

MyProject/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="{% static 'food/style.css' %}" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">FoodZone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'food:create_item' %}">Add Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Delete Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">View Items</a>
        </li>
        <li class="nav-link nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
            <a href="{% url 'profile' %}">Profile</a>
          {% else %}
            <a href="{% url 'login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{message}}
      </div>
    {% endfor %}
  {% endif %}

{% block body %}
{% endblock %}

</body>
</html>

MyProject/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

    <class class="container">
        <class class="row offset-1">
            <class class="col-md-6">
                <img height="250px;" src="{{ item.item_image }}" />
            </class>
            <class class="col-md-6">
                <h1>{{ item.item_name }}</h1>
                <h1>{{ item.item_desc }}</h1>
                <h1>{{ item.item_price }}</h1>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </class>
        </class>
    </class>

{% endblock %}

MyProject/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block body %}

    {% for item in item_list %}
        <div class="card mb-3 offset-md-2" style="max-width: 550px; margin-top:10px">
          <div class="row">
            <div class="col-md-4">
              <img src="{{ item.item_image }}" class="img-fluid rounded-start" style="width:280px; height: 150px;" />
            </div>
            <div class="col-md-4">
              <div class="card-body">
                <h5 class="card-title">{{ item.item_name }}</h5>
                <p class="card-text">{{ item.item_desc }}</p>
                <p class="card-text">{{ item.user_name }}</p>
                <p class="card-text"><small class="text-muted">${{ item.item_price }}</small></p>
              </div>
            </div>
            <div class="col-md-4" style="margin-top: 5px;">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success float-end">View Details</a>
                <a type="button" class="btn btn-success float-end" style="margin-right:6px; margin-top:5px;">Add Item</a>
            </div>

          </div>
        </div>

    {% endfor %}

{% endblock %}

MyProject/food/templates/food/item_delete.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to Delete? {{ item.item_name }}</h2>
    <button type="submit" name="delete">Confirm</button>

</form>

{% endblock %}

MyProject/food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" name="Submit">Submit</button>
</form>

{% endblock %}

MyProject/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info align-center">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn-info" type="submit" style="margin-top:5px;">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

MyProject/users/templates/users/logout.html
<h1>You have been logged out</h1>

MyProject/users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}">

MyProject/users/templates/users/register.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>